# Generated by Django 4.2.2 on 2023-06-22 08:02

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=["name"]),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=["name"]),
        ),
    ]
