# Generated by Django 4.2.2 on 2023-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_message_deleted_at_message_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.TextField(choices=[("public", "Public"), ("private", "Private")], default="Public"),
        ),
    ]
