# Generated by Django 4.2.2 on 2023-07-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_reactiontype_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.message",
            ),
        ),
    ]
