# Generated by Django 4.2.2 on 2023-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://avatars.dicebear.com/api/bottts/default.svg'),
        ),
    ]
