# Generated by Django 4.2.2 on 2023-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_rename_invitee_id_roominvitation_invitee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
