name: Deploy documentation site

on:
  push:
    paths:
    - 'docs/**'
    - '.github/workflows/deploy-docs.yml' 
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Deploys
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: Setup cargo and Rust toolchain
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: 'Build and deploy'
      shell: bash
      run: |
        cargo install --git https://github.com/Doctave/doctave --tag 0.4.2
        doctave build --release --allow-failed-checks
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        build_dir: site/